# Generated by Django 5.1.2 on 2024-10-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employer', 'Работодатель'), ('applicant', 'Соискатель')], default='applicant', max_length=10),
            preserve_default=False,
        ),
    ]
