# Generated by Django 5.1.2 on 2025-01-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_customuser_city_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='citizenship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='index',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ok',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sk',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tg',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vk',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wa',
            field=models.URLField(blank=True),
        ),
    ]
