# Generated by Django 5.1.2 on 2025-01-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_customuser_address_customuser_citizenship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='index',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ok',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sk',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tg',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vk',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wa',
        ),
    ]
