# Generated by Django 5.1.2 on 2025-01-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_usercity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCity',
        ),
    ]
