# Generated by Django 5.1.2 on 2025-01-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_delete_usercity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
