# Generated by Django 5.1.2 on 2025-01-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_customuser_patronymic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='patronymic',
        ),
    ]
