# Generated by Django 5.1.2 on 2025-01-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_customuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='citizenship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ok_link',
            field=models.URLField(blank=True, null=True, verbose_name='Одноклассники'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skype_link',
            field=models.URLField(blank=True, null=True, verbose_name='Skype'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vk_link',
            field=models.URLField(blank=True, null=True, verbose_name='ВКонтакте'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
    ]
