# Generated by Django 5.1.2 on 2025-01-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_customuser_address_customuser_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ok_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Одноклассники'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skype_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vk_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='WhatsApp'),
        ),
    ]
