# Generated by Django 5.1.2 on 2025-01-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='work_status',
            field=models.CharField(choices=[('SW', 'В поиске работы'), ('NSW', 'Не ищу работу')], default='SW', max_length=3, verbose_name='Статус на сайте'),
        ),
    ]
