# Generated by Django 5.1.2 on 2025-01-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_customuser_work_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='work_status',
        ),
    ]
