# Generated by Django 5.1.2 on 2025-01-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_remove_customuser_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='work_status',
            field=models.CharField(choices=[('S', 'В поиске работы'), ('N', 'Не ищу работу')], default='S', max_length=1, verbose_name='Статус на сайте'),
        ),
    ]
