# Generated by Django 5.1.2 on 2025-01-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_customuser_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_network_show',
            field=models.BooleanField(default=False, verbose_name='Отображать ссылки на профили социальных сетей в резюме'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telephone_show',
            field=models.BooleanField(default=False, verbose_name='Отображать номер телефона в резюме'),
        ),
    ]
