# Generated by Django 5.1.2 on 2025-01-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_customuser_social_network_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='inn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kpp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ogr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ОГРН/ОГРНИП'),
        ),
    ]
