# Generated by Django 5.1.2 on 2025-01-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_customuser_inn_customuser_kpp_customuser_ogr'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='site_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Сайт компании'),
        ),
    ]
