# Generated by Django 5.1.2 on 2025-01-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_customuser_site_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании'),
        ),
    ]
