# Generated by Django 5.1.2 on 2025-01-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_alter_customuser_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail компании'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail физического лица'),
        ),
    ]
