# Generated by Django 5.1.2 on 2025-01-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание компании'),
        ),
    ]
