# Generated by Django 5.1.2 on 2025-02-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
