# Generated by Django 5.1.2 on 2025-02-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_alter_vacancy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='levels',
            field=models.CharField(blank=True, choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=255, verbose_name='Уровень'),
        ),
    ]
