# Generated by Django 5.1.2 on 2025-02-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_vacancy_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=50, unique=True, verbose_name='Уровень')),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='levels',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='levels',
            field=models.ManyToManyField(blank=True, to='main_app.level', verbose_name='Уровни'),
        ),
    ]
