# Generated by Django 5.1.2 on 2025-02-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_alter_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='levels',
            field=models.ManyToManyField(to='main_app.level', verbose_name='Уровни'),
        ),
    ]
