# Generated by Django 5.1.2 on 2025-02-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_alter_vacancy_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=50, unique=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='levels',
            field=models.ManyToManyField(blank=True, to='main_app.level', verbose_name='Уровни'),
        ),
    ]
