# Generated by Django 5.1.2 on 2025-02-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0046_alter_vacancy_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='levels',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
