# Generated by Django 5.1.2 on 2025-02-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0047_remove_vacancy_levels_delete_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='level',
            field=models.CharField(blank=True, choices=[('JUNIOR', 'Junior'), ('MIDDLE', 'Middle'), ('SENIOR', 'Senior')], help_text='Выберите один или несколько уровней', max_length=50, verbose_name='Уровень'),
        ),
    ]
