# Generated by Django 5.1.2 on 2025-02-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0048_vacancy_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='level',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='levels',
            field=models.ManyToManyField(blank=True, help_text='Выберите один или несколько уровней', to='main_app.level', verbose_name='Уровни'),
        ),
    ]
