# Generated by Django 5.1.2 on 2025-02-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0050_remove_vacancy_levels_delete_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='levels',
            field=models.CharField(blank=True, max_length=50, verbose_name='Уровни'),
        ),
    ]
