# Generated by Django 5.1.2 on 2025-02-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0051_vacancy_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='desc_1',
            field=models.TextField(blank=True, null=True, verbose_name='Описание вакансии'),
        ),
    ]
