# Generated by Django 5.1.2 on 2025-02-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0052_vacancy_desc_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='desc_2',
            field=models.TextField(blank=True, null=True, verbose_name='Описание тестового задания'),
        ),
    ]
