# Generated by Django 5.1.2 on 2025-02-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0053_vacancy_desc_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='address_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='city_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='postal_code_1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Индекс'),
        ),
    ]
