# Generated by Django 5.1.2 on 2025-02-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0054_vacancy_address_1_vacancy_city_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employment_hidden',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип занятости'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='specialization_hidden',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_hidden',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='levels',
            field=models.CharField(blank=True, max_length=50, verbose_name='Уровни компетенций'),
        ),
    ]
