# Generated by Django 5.1.2 on 2025-02-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0055_vacancy_employment_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='education_hidden',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='languages_hidden',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Владение языками'),
        ),
    ]
