# Generated by Django 5.1.2 on 2025-02-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_vacancy_education_hidden_vacancy_languages_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='relocation',
            field=models.BooleanField(default=False, verbose_name='Релокейт соискателя'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='resume_required',
            field=models.BooleanField(default=False, verbose_name='Обязательно наличие резюме'),
        ),
    ]
