# Generated by Django 5.1.2 on 2025-02-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0057_vacancy_relocation_vacancy_resume_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='exp',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Нет опыта'), (1, 'От 1 до 3 лет'), (2, 'От 3 до 6 лет'), (3, 'Более 6')], null=True, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='money',
            field=models.IntegerField(blank=True, choices=[(1, 'На руки'), (0, 'До вычета налогов')], default=1, null=True, verbose_name='Тип зарплаты'),
        ),
    ]
