# Generated by Django 5.1.2 on 2025-02-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0058_vacancy_exp_vacancy_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='test_file',
            field=models.FileField(blank=True, null=True, upload_to='vacancy_files/', verbose_name='Файл тестового задания'),
        ),
    ]
