# Generated by Django 5.1.2 on 2025-02-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0059_vacancy_test_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='test_file',
        ),
    ]
