# Generated by Django 5.1.2 on 2025-02-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0060_remove_vacancy_test_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='skills_hidden',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые навыки'),
        ),
    ]
