# Generated by Django 5.1.2 on 2025-02-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0061_vacancy_skills_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary_from_1',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Зарплата от'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_to_1',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Зарплата до'),
        ),
    ]
