# Generated by Django 5.1.2 on 2025-02-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0062_vacancy_salary_from_1_vacancy_salary_to_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='currency_1',
            field=models.CharField(choices=[('RUB', '₽'), ('USD', '$'), ('EUR', '€'), ('CNY', '¥')], default='RUB', max_length=3, verbose_name='Валюта зарплаты'),
        ),
    ]
