# Generated by Django 5.1.2 on 2025-02-07 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0063_vacancy_currency_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('unique_link', models.CharField(max_length=255, unique=True, verbose_name='Уникальная ссылка')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='main_app.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Интервью',
                'verbose_name_plural': 'Интервью',
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('audio', models.FileField(blank=True, null=True, upload_to='interview_audio/', verbose_name='Аудиофайл')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main_app.interview', verbose_name='Интервью')),
            ],
            options={
                'verbose_name': 'Вопрос интервью',
                'verbose_name_plural': 'Вопросы интервью',
            },
        ),
    ]
