# Generated by Django 5.1.2 on 2025-02-07 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0064_interview_interviewquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='applicant',
            field=models.ForeignKey(limit_choices_to={'role': 'applicant'}, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель'),
        ),
    ]
