# Generated by Django 5.1.2 on 2025-02-07 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0065_alter_interview_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='unique_link',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Уникальная ссылка'),
        ),
    ]
