# Generated by Django 5.1.2 on 2025-02-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0066_alter_interview_unique_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='audio',
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='interview_videos/', verbose_name='Видеофайл'),
        ),
    ]
