# Generated by Django 5.1.2 on 2025-02-09 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0067_remove_interviewquestion_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='interview_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='Видеофайл'),
        ),
    ]
