# Generated by Django 5.1.2 on 2025-02-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0068_alter_interviewquestion_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='audio_response',
            field=models.FileField(blank=True, null=True, upload_to='interview_audio_responses/', verbose_name='Аудио ответа'),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='interview_videos/', verbose_name='Видеофайл'),
        ),
    ]
