# Generated by Django 5.1.2 on 2025-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0069_interviewquestion_audio_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='audio_response',
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='question_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок вопроса'),
        ),
    ]
