# Generated by Django 5.1.2 on 2025-02-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0070_remove_interviewquestion_audio_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='text_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ответа'),
        ),
    ]
