# Generated by Django 5.1.2 on 2025-04-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0073_vacancyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=10, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
