# Generated by Django 5.1.2 on 2025-04-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0074_interview_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='gender',
            field=models.CharField(choices=[('МУЖ', 'Мужской'), ('ЖЕН', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
    ]
