# Generated by Django 5.1.2 on 2025-04-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0075_alter_interview_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='hrname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя HR'),
        ),
    ]
