# Generated by Django 5.1.2 on 2025-04-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0076_interview_hrname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='hrname',
            new_name='hr_name',
        ),
    ]
