# Generated by Django 5.1.2 on 2025-05-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0077_rename_hrname_interview_hr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='match_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Например: 87.50 — означает 87.5% соответствия требованиям вакансии', max_digits=5, null=True, verbose_name='Процент соответствия вакансии'),
        ),
    ]
