# Generated by Django 5.1.2 on 2025-05-03 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0078_interview_match_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyresponse',
            name='interview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response', to='main_app.interview', verbose_name='Интервью'),
        ),
    ]
