# Generated by Django 5.1.2 on 2025-05-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0079_vacancyresponse_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyresponse',
            name='interview',
        ),
    ]
