# Generated by Django 5.1.2 on 2025-05-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0080_remove_vacancyresponse_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='video_response',
            field=models.FileField(blank=True, null=True, upload_to='interview_video_responses/', verbose_name='Видео ответа кандидата'),
        ),
    ]
