# Generated by Django 5.1.2 on 2025-05-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0081_interviewquestion_video_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='video_response',
        ),
        migrations.CreateModel(
            name='VideoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='interview_video_responses/', verbose_name='Файл видеоответа')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_responses', to='main_app.interviewquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Видеоответ',
                'verbose_name_plural': 'Видеоответы',
            },
        ),
    ]
