# Generated by Django 5.1.2 on 2025-05-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0082_remove_interviewquestion_video_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='summary',
            field=models.TextField(blank=True, help_text='Краткое содержание интервью, полученное от ИИ', null=True, verbose_name='Суммаризация интервью'),
        ),
    ]
