# Generated by Django 5.1.2 on 2025-09-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0083_interview_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='hr_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hr_photos/', verbose_name='Фото рекрутера'),
        ),
    ]
