# Generated by Django 5.1.2 on 2025-09-07 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0084_interview_hr_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализация')),
                ('key_skills', models.JSONField(default=list, verbose_name='Ключевые навыки')),
                ('key_responsibilities', models.JSONField(default=list, verbose_name='Ключевые обязанности')),
                ('work_experience', models.JSONField(default=list, verbose_name='Опыт работы (описание)')),
                ('general_experience_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Общий стаж (в годах)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-created_at'],
            },
        ),
    ]
