# Generated by Django 5.1.2 on 2025-09-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0085_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='employer',
            new_name='user',
        ),
    ]
